### ISSUE TITLE
[Bug]: We are unable to process your request at the moment

### ISSUE THREAD

**Issue by roman4yk** [swar/nba_api#268] opened 2022-10-04 09:40 UTC
### NBA API Version

1.1.11

### Issue

Hello. When I send a request to the https://stats.nba.com/stats/scoreboardv3 endpoint, I get a response from the server "We are unable to process your request at the moment". Everything worked fine until today, tell me how to solve this problem.

**Comment by NickFerd** [comment] 2022-10-05 17:27
Have the same issue, looks like global problem with stats.nba.com. Would appreciate any info if anyone knows

**Comment by muabdali** [comment] 2022-10-10 13:46
Works for me, is it still broken for you two?

**Comment by NickFerd** [comment] 2022-10-10 14:14
Yes, still have problems with it, can you share headers if you use custom ones?
found that i can get the proper answer if add to headers:
 'Origin': 'https://stats.nba.com'

**Comment by muabdali** [comment] 2022-10-10 14:21
Yes I use custom headers. I remember somewhere in the documentation it was recommended to use 
`custom_headers = {
    'Host': 'stats.nba.com',
    'Connection': 'keep-alive',
    'Cache-Control': 'max-age=0',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',`

**Comment by muabdali** [comment] 2022-10-16 08:37
any luck?

**Comment by rsforbes** [comment] 2022-10-16 17:58
Duplicate of #292

**Closed** 2022-10-16 17:59 UTC
Labels: duplicate
