### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nicolasgomasjaya** [swar/nba_api#341] opened 2023-05-06 16:24 UTC
### NBA API Version

1.2

### Issue

Have no problem with LeagueGameFinder, but always have error with all boxscores. Here's the error message:

### Code

boxscore = ep.BoxScoreAdvancedV2(game_ids[0], range_type=2, headers=headers).get_data_frames()[0]

Output:
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In[8], line 1
----> 1 boxscore = ep.BoxScoreAdvancedV2(game_ids[0], range_type=2, headers=headers).get_data_frames()[0]

File [~/miniconda3/envs/nba/lib/python3.11/site-packages/nba_api/stats/endpoints/boxscoreadvancedv2.py:40](https://file+.vscode-resource.vscode-cdn.net/Users/nicolasgomasjaya/Documents/Code/Project/NBA%20Prediction/archive/~/miniconda3/envs/nba/lib/python3.11/site-packages/nba_api/stats/endpoints/boxscoreadvancedv2.py:40), in BoxScoreAdvancedV2.__init__(self, game_id, end_period, end_range, range_type, start_period, start_range, proxy, headers, timeout, get_request)
     31 self.parameters = {
     32         'GameID': game_id,
     33         'EndPeriod': end_period,
   (...)
     37         'StartRange': start_range
     38 }
     39 if get_request:
---> 40     self.get_request()

File [~/miniconda3/envs/nba/lib/python3.11/site-packages/nba_api/stats/endpoints/boxscoreadvancedv2.py:50](https://file+.vscode-resource.vscode-cdn.net/Users/nicolasgomasjaya/Documents/Code/Project/NBA%20Prediction/archive/~/miniconda3/envs/nba/lib/python3.11/site-packages/nba_api/stats/endpoints/boxscoreadvancedv2.py:50), in BoxScoreAdvancedV2.get_request(self)
     42 def get_request(self):
     43     self.nba_response = NBAStatsHTTP().send_api_request(
     44         endpoint=self.endpoint,
     45         parameters=self.parameters,
   (...)
     48         timeout=self.timeout,
     49     )
---> 50     self.load_response()
...
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by blizzi2** [comment] 2023-05-26 08:11
I have the same problem. Can somebody please help?

**Comment by rsforbes** [comment] 2023-05-26 13:07
I can take a look at this over the weekend. Was this working before and stopped working, or is this the first time using that method and thus may have never worked?

**Comment by blizzi2** [comment] 2023-05-26 13:20
This error actually occurs to me when I use playergamelog.PlayerGameLog . It worked for me many times before

**Comment by nicolasgomasjaya** [comment] 2023-05-26 15:55
it worked before but stop working

**Comment by ChristopherBanas** [comment] 2023-06-14 01:07
This looks the same as https://github.com/swar/nba_api/issues/346. It was working previously and then stopped. Looks like it's something on nba.com's side

**Comment by rsforbes** [comment] 2023-06-14 10:32
I ran tests on these endpoints this morning. Both are working; however, they may not be working if certain parameters are passed. 

Example:
```
# Success  (RangeType=0)
https://stats.nba.com/stats/boxscoreadvancedv2?GameID=0022200971&StartPeriod=0&EndPeriod=0&StartRange=0&EndRange=0&RangeType=0 

# Success  (Omit RangeType)
https://stats.nba.com/stats/boxscoreadvancedv2?GameID=0022200971&StartPeriod=0&EndPeriod=0&StartRange=0&EndRange=0

# Failure (RangeType=2
https://stats.nba.com/stats/boxscoreadvancedv2?GameID=0022200971&StartPeriod=0&EndPeriod=0&StartRange=0&EndRange=0&RangeType=2
```

I've also tested the PlayerGameLog, and it is successful as well.
```
# Success 
https://stats.nba.com/stats/playergamelogs?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&MeasureType=Base&Month=0&OppTeamID=0&OpponentTeamID=0&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerID=1631105&PlusMinus=N&Rank=N&Season=2022-23&SeasonType=Regular Season
```

What are the parameters you are sending, what is your expectation, and do you have a working example from the NBA's Stats site?

In #346 it appears the call with specific params may not even be working for the NBA's own usage within their site. TBD.

**Comment by rsforbes** [comment] 2023-06-14 11:16
I am merging this with #346. I've placed a proposal there that we simply force these values to be standard values under the covers. I'm unable to find where the values result in a different outcome—taking feedback on #346.

**Comment by rsforbes** [comment] 2023-06-14 11:17
Duplicate of #346

**Closed by rsforbes** 2023-06-14 11:16 UTC
Labels: bug, triage
